# Generated by Django 3.1 on 2020-09-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('nome_empresa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_postagem', to='socialRede.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'CURTIR'), ('A', 'AMEI'), ('R', 'RISOS'), ('G', 'GRRR'), ('B', 'RUIM')], max_length=1)),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comentario', to='socialRede.perfil')),
                ('postagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postagem_reacao', to='socialRede.postagem')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to='socialRede.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_perfil', to='socialRede.perfil')),
                ('postagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postagem_comentario', to='socialRede.postagem')),
            ],
        ),
    ]
